#!/bin/bash

javadoc -private -author -link https://docs.oracle.com/en/java/javase/17/docs/api/ \
-d ../javadoc ../java-solutions/info/kgeorgiy/ja/urazov/implementor/Implementor.java \
../../java-advanced-2022/modules/info.kgeorgiy.java.advanced.implementor/info/kgeorgiy/java/advanced/implementor/*Impler*.java

